# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hidden_phone',
            field=models.BooleanField(default=False),
        ),
    ]
