# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 11:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_blocked_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='user_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_blocks', to=settings.AUTH_USER_MODEL),
        ),
    ]
