# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 19:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_user_blocked_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blocked_users',
            field=models.ManyToManyField(related_name='blocked_me', through='users.BlackList', to='users.User'),
        ),
    ]
