# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 20:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_user_blocked_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='owner',
            new_name='user_from',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='to',
            new_name='user_to',
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together=set([('user_from', 'user_to')]),
        ),
    ]
