# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 20:52
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20161012_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='', storage=django.core.files.storage.FileSystemStorage(base_url='http://localhost:8000/media/'), upload_to='images/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
