# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20161012_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='foo',
            field=models.BooleanField(default=False),
        ),
    ]
