# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 15:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_user_foo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blacklist',
            name='active',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='active',
        ),
        migrations.AddField(
            model_name='user',
            name='blocked_users',
            field=models.ManyToManyField(related_name='blocked_me', through='users.BlackList', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='contacted_users',
            field=models.ManyToManyField(related_name='contacted_me', through='users.Contact', to=settings.AUTH_USER_MODEL),
        ),
    ]
