# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 12:35
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20161115_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tmp',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+79250741413', max_length=128),
            preserve_default=False,
        ),
    ]
