# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_auto_20161017_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='king',
        ),
        migrations.AddField(
            model_name='member',
            name='king',
            field=models.BooleanField(default=False),
        ),
    ]
