# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 14:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_auto_20161018_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meeting',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 10, 18, 14, 48, 10, 982259, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
