# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_auto_20161018_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
