# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 15:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0007_auto_20161018_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='active',
        ),
        migrations.AddField(
            model_name='meeting',
            name='users',
            field=models.ManyToManyField(related_name='meetings', through='meetings.Member', to=settings.AUTH_USER_MODEL),
        ),
    ]
