# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0008_auto_20161019_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
