# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0011_auto_20161115_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='destination_lat',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting',
            name='destination_lon',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
