# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0012_auto_20161115_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='destination_lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='destination_lon',
            field=models.FloatField(default=0.0),
        ),
    ]
